export enum OrderStatus {
  PENDING = 'PENDING',
  SENT_TO_KITCHEN = 'SENT_TO_KITCHEN',
  IN_PREPARATION = 'IN_PREPARATION',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  PICKED_UP = 'PICKED_UP',
  SERVED = 'SERVED',
  CANCELLED = 'CANCELLED',
  BILLED = 'BILLED',
}
